WEBSIMD128-OBJS-$(CONFIG_H264CHROMA)      += webassembly/h264chroma_websimd128.o
OBJS-$(CONFIG_H264CHROMA)                 += webassembly/h264chroma_init_wasm.o

OBJS-$(CONFIG_H264DSP)                    += webassembly/h264dsp_init_wasm.o
WEBSIMD128-OBJS-$(CONFIG_H264DSP)         += webassembly/h264dsp_websimd128.o

OBJS-$(CONFIG_H264QPEL)                   += webassembly/h264qpel_init_wasm.o
WEBSIMD128-OBJS-$(CONFIG_H264QPEL)         += webassembly/h264qpel_websimd128.o

OBJS-$(CONFIG_H264PRED)                   += webassembly/h264pred_init_wasm.o
WEBSIMD128-OBJS-$(CONFIG_H264PRED)         += webassembly/h264pred_websimd128.o