SIMD128-OBJS-$(CONFIG_H264CHROMA)      += wasm/h264/h264chroma_websimd128.o
OBJS-$(CONFIG_H264CHROMA)                 += wasm/h264/h264chroma_init.o

OBJS-$(CONFIG_H264DSP)                    += wasm/h264/h264dsp_init.o
SIMD128-OBJS-$(CONFIG_H264DSP)         += wasm/h264/h264dsp_websimd128.o

OBJS-$(CONFIG_H264QPEL)                   += wasm/h264/h264qpel_init.o
SIMD128-OBJS-$(CONFIG_H264QPEL)         += wasm/h264/h264qpel_websimd128.o

OBJS-$(CONFIG_H264PRED)                   += wasm/h264/h264pred_init.o
SIMD128-OBJS-$(CONFIG_H264PRED)         += wasm/h264/h264pred_websimd128.o